[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/go-logger"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/Financial-Times/http-handlers-go"
  version = "0.1.1"

[[constraint]]
  name = "github.com/Financial-Times/neo-model-utils-go"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/neo-utils-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/Financial-Times/transactionid-utils-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Financial-Times/up-rw-app-api-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jmcvetta/neoism"
  source = "github.com/Financial-Times/neoism"
  version = "^2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[prune]
  go-tests = true
  unused-packages = true
